version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Berlin
  ignore:
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
